### PR TITLE
R is terrible, do not use it

### PR DESCRIPTION
**Pull request by Ironholds**
Use compiled code instead! Ye can execute this kind of check in C perfectly happily and faster, too, even if it's a one-off call.

Will handle it for sumprod too if(change_merged && drew_does_not_get_there_first)

### CODE REVIEW

**Comment by wrathematics** [comment]
Funny story, the professor I did this for really does not like R. But his preference is Matlab 😉

**Comment by wrathematics** [comment]
Oh wait, this is a real PR.

I always forget R has `TYPEOF` because `typeof` is a GNU C extension that I go out of my way to avoid.

**Comment by Ironholds** [comment]
Yeah, I forget unless I bookmark Kevin's excellent article on compiled-side type-handling.

**Comment by wrathematics** [comment]
Whoops, forgot to thank you (I'm a little disoriented at the moment!).  Thanks!

Regarding my earlier comment, I assumed you `rm -rf R/` as a joke about how I have a tendency to do things in C.  Also added you as a contributer in the DESCRIPTION.

**Pull request merged**
